services:
  test:
    build: .
    command: pytest -v

  test-cov:
    build: .
    command: pytest --cov=app --cov-report=term-missing

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
