[project]
name = "student-materials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standart]>=0.128.0",
    "redis>=7.1.0",
]
